#!/bin/sh
brightness=$(brightnessctl  -d 'intel_backlight' g) 
full_brightness=$(brightnessctl  -d 'intel_backlight' m) 
brightness_percentage=$(expr $brightness \* 100 / $full_brightness)
killall dunst
notify-send -i /usr/share/icons/Win11-dark/status@2x/24/display-brightness-symbolic.svg " Brightness " " $brightness_percentage% "
